############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 7

[[main]]
name = "Terms and Conditions"
url = "terms-and-conditions/"
weight = 5

[[main]]
name = "Contact Me"
url = "contact-me/"
weight = 6

