baseURL = 'https://devmlops-hugo.pages.dev/'
languageCode = 'en-us'
title = 'Dev + ML + Ops'
theme = 'iwriter'
ga4_id = 'G-JBCMXLR46W'
[menu]

  [[menu.main]]
    identifier = "blog"
    name = "All Posts"
    url = "/posts/"
    weight = 3
